callbacks:
  - name: FreezeModule
    # the backbone.conv1 layer should also be fine-tuned.
    args:
      modules:
        - layer1
        - layer2
        - layer3
        - layer4
      freeze_at_start: true
      train_bn: true
