callbacks:
  FreezeBackbone:
    name: FreezeModule
    # the backbone.conv1 layer should also be fine-tuned.
    args:
      modules:
        - backbone.layer1
        - backbone.layer2
        - backbone.layer3
        - backbone.layer4
      freeze_at_start: true
      train_bn: true
