# Use MLDecoderClassificationHead
model:
  modules:
    classifier:
      name: MLDecoderClassificationHead
      input: "output"
      args:
        initial_num_features: "{model.modules.backbone.out_features}"
        decoder_embedding: 768
        dropout: 0.2
        num_classes: "{const.num_classes}"
        return_logits: True # return logits instead of softmax probability.
        zsl: False
