# use backbone from https://github.com/Alibaba-MIIL/ImageNet21K
model:
  modules:
    backbone:
      name: "TimmNetwork"
      args:
        name: resnet50
        args:
          pretrained: false
      out_features: 2048

      weights:
        is_ckpt: True
        url: "https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/ImageNet_21K_P/models/resnet50_miil_21k.pth"
