# use backbone from https://github.com/Alibaba-MIIL/ImageNet21K
model:
  modules:
    backbone:
      name: "TimmNetwork"
      args:
        name: "vit_base_patch16_224_miil_in21k"
        args:
          pretrained: True
      out_features: 768
    classifier:
      args:
        reduction: "none"
