# use backbone from https://github.com/Alibaba-MIIL/ImageNet21K
model:
  modules:
    backbone:
      name: "TimmNetwork"
      args:
        name: "tresnet_m_miil_in21k"
        args:
          pretrained: True
      out_features: 2048
