training:
  metrics:
    class-avg-accuracy:
      when: "trn,val,test"
      name: TorchMetric
      args:
        name: "Accuracy"
        args:
          average: "macro"
          num_classes: "{const.num_classes}"
      update:
        preds: "logits"
        target: "y"
