name: "resnet50-bs265-sgd-lr0.01"

model:
  modules:
    backbone:
      name: "TimmNetwork"
      args:
        name: resnet50
        args:
          pretrained: false
      out_features: 2048

    classifier:
      name: "ClassificationHead"
      input: "output"
      args:
        reduction: "gap"
        in_features: "{model.modules.backbone.out_features}"
        dropout: 0.2
        num_classes: "{const.num_classes}"
        return_logits: True # return logits instead of softmax probability.
    loss_fn:
      name: "CrossEntropyLoss"

callbacks:
  ModelCheckpoint:
    name: LightningCallback
    args:
      name: ModelCheckpoint
      args:
        monitor: "epoch_val/accuracy"
        mode: "max"
        save_last: True
        save_top_k: 1
  LearningRateMonitor:
    name: LightningCallback
    args:
      name: "LearningRateMonitor"
      args:
        logging_interval: "epoch"

training:
  ID: "ClassificationTrainer"

  epochs: 200
  lr: 0.01
  batch_size: 256
  optimizer: "sgd"
  optimizer_cfg:
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler:
    name: "cosine"
    args: {}
    cfg:
      interval: "epoch"
  lr_warmup:
    multiplier: 1
    total_epoch: 5

  metrics:
    loss:
      when: "trn,val,test"
      name: TorchMetric
      args:
        name: "MeanMetric"
      update:
        value: "cls_loss"
    confusion_matrix:
      interval: { "trn": 50 }
      when: "trn,val,test"
      name: TorchMetric
      args:
        name: "ConfusionMatrix"
        args:
          num_classes: "{const.num_classes}"
      update:
        preds: "logits"
        target: "y"
    accuracy:
      when: "trn,val,test"
      name: TorchMetric
      args:
        name: "Accuracy"
      update:
        preds: "logits"
        target: "y"

validation:
  batch_size: 256

debug:
  network_summary:
    input_shape: [3, 224, 224]

# other useful configs.
wandb:
  project: "kt_food_classification_challenge_2022"
  group: "baseline"
