dataset:
  dataset_base_cfg:
    args:
      args:
        download: False
  dataset_subset_cfg:
    trn:
      args:
        args:
          download: False
    val:
      args:
        args:
          download: False
