# base config for training.
name: "default-experiment"
VERBOSE: "DEFAULT"
DEBUG_MODE: False
seed: True

trainer:
  strategy: "dp"
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 5
  precision: 32

# change values based on setting
dataloader:
  base_dataloader:
    num_workers: 2
    pin_memory: True
    shuffle: True
    prefetch_factor: 2
  trn:
    shuffle: True
  val:
    shuffle: False
    drop_last: False
