# Implement SWA of weights, proposed in the paper:
# Averaging Weights Leads to Wider Optima and Better Generalization, 2018
# about SWA: https://pytorch.org/blog/pytorch-1.6-now-includes-stochastic-weight-averaging/
# docs: https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.StochasticWeightAveraging.html#pytorch_lightning.callbacks.StochasticWeightAveraging
# TODO build wrapper for StochasticWeightAveraging so `avg_fn` argument can be used.
callbacks:
  StochasticWeightAveraging:
    name: LightningCallback
    args:
      name: "StochasticWeightAveraging"
      args:
        swa_lrs: 0.02 # typicall x0.2 ~ x0.5 of initial lr
        swa_epoch_start: 0.75
        annealing_epochs: 5 # smooth the connection between lr schedule and SWA.
        annealing_strategy: "cos"
        avg_fn: null
