data:
  samples_per_gpu: 64
  test_dataloader:
    samples_per_gpu: 32
  val_dataloader:
    samples_per_gpu: 32
  workers_per_gpu: 2
data_root: data/mpii
dist_params:
  backend: nccl
evaluation:
  interval: 10
  metric: PCKh
  save_best: PCKh
load_from: null
log_config:
  hooks:
  - type: TextLoggerHook
  interval: 50
log_level: INFO
lr_config:
  policy: step
  step:
  - 170
  - 200
  warmup: linear
  warmup_iters: 500
  warmup_ratio: 0.001
model:
  backbone:
    extra:
      stage1:
        block: BOTTLENECK
        num_blocks:
        - 4
        num_branches: 1
        num_channels:
        - 64
        num_modules: 1
      stage2:
        block: BASIC
        num_blocks:
        - 4
        - 4
        num_branches: 2
        num_channels:
        - 32
        - 64
        num_modules: 1
      stage3:
        block: BASIC
        num_blocks:
        - 4
        - 4
        - 4
        num_branches: 3
        num_channels:
        - 32
        - 64
        - 128
        num_modules: 4
      stage4:
        block: BASIC
        num_blocks:
        - 4
        - 4
        - 4
        - 4
        num_branches: 4
        num_channels:
        - 32
        - 64
        - 128
        - 256
        num_modules: 3
    in_channels: 3
    type: HRNet
  keypoint_head:
    extra:
      final_conv_kernel: 1
    in_channels: 32
    loss_keypoint:
      type: JointsMSELoss
      use_target_weight: true
    num_deconv_layers: 0
    out_channels: 16
    type: TopdownHeatmapSimpleHead
  pretrained: https://download.openmmlab.com/mmpose/pretrain_models/hrnet_w32-36af842e.pth
  test_cfg:
    flip_test: true
    modulate_kernel: 11
    post_process: default
    shift_heatmap: true
  train_cfg: {}
  type: TopDown
mp_start_method: fork
opencv_num_threads: 0
optimizer:
  lr: 0.0005
  type: Adam
optimizer_config:
  grad_clip: null
resume_from: null
test_pipeline:
- type: LoadImageFromFile
- padding: 1.25
  type: TopDownGetBboxCenterScale
- type: TopDownAffine
- type: ToTensor
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeTensor
- keys:
  - img
  meta_keys:
  - image_file
  - center
  - scale
  - rotation
  - flip_pairs
  type: Collect
total_epochs: 210
train_pipeline:
- type: LoadImageFromFile
- padding: 1.25
  type: TopDownGetBboxCenterScale
- flip_prob: 0.5
  type: TopDownRandomFlip
- rot_factor: 40
  scale_factor: 0.5
  type: TopDownGetRandomScaleRotation
- type: TopDownAffine
- type: ToTensor
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeTensor
- sigma: 2
  type: TopDownGenerateTarget
- keys:
  - img
  - target
  - target_weight
  meta_keys:
  - image_file
  - joints_3d
  - joints_3d_visible
  - center
  - scale
  - rotation
  - flip_pairs
  type: Collect
val_pipeline:
- type: LoadImageFromFile
- padding: 1.25
  type: TopDownGetBboxCenterScale
- type: TopDownAffine
- type: ToTensor
- mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeTensor
- keys:
  - img
  meta_keys:
  - image_file
  - center
  - scale
  - rotation
  - flip_pairs
  type: Collect
workflow:
- - train
  - 1
