transform:
  [
    [
      "trn",
      [
        {
          "name": "TorchvisionTransforms",
          "args": { "name": "RandomHorizontalFlip" },
        },
        { "name": "TorchvisionTransforms", "args": { "name": "RandomVerticalFlip" } },
        {
          "name": "TorchvisionTransforms",
          "args": { "name": "RandomRotation", "args": { "degrees": [0, 360] } },
        },

        {
          "name": "TorchvisionTransforms",
          "args":
            {
              "name": "TrivialAugmentWide",
              "args": { "num_magnitude_bins": 31 },
            },
        },
      ],
    ],
    ["trn,val", [{ "name": "ClassificationLabelEncoder" }]],

    [
      "trn,val,pred",
      [
        { "name": "Resize", "args": { "size": [224, 224] } },
        { "name": "ImageToTensor", "args": {} },
        {
          "name": "Normalize",
          "args":
            {
              "mean": [0.25252014, 0.12918881, 0.12411932],
              "std": [0.24537923, 0.17195621, 0.17269008],
            },
        },
      ],
    ],
  ]
